# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.7.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.7.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/maluramichael/Development/Private/pancake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/maluramichael/Development/Private/pancake

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.7.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.6.3/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.7.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.7.1/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.7.1/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.7.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/maluramichael/Development/Private/pancake/CMakeFiles /Users/maluramichael/Development/Private/pancake/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/maluramichael/Development/Private/pancake/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pancake

# Build rule for target.
pancake: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pancake
.PHONY : pancake

# fast build rule for target.
pancake/fast:
	$(MAKE) -f CMakeFiles/pancake.dir/build.make CMakeFiles/pancake.dir/build
.PHONY : pancake/fast

src/Log.o: src/Log.cpp.o

.PHONY : src/Log.o

# target to build an object file
src/Log.cpp.o:
	$(MAKE) -f CMakeFiles/pancake.dir/build.make CMakeFiles/pancake.dir/src/Log.cpp.o
.PHONY : src/Log.cpp.o

src/Log.i: src/Log.cpp.i

.PHONY : src/Log.i

# target to preprocess a source file
src/Log.cpp.i:
	$(MAKE) -f CMakeFiles/pancake.dir/build.make CMakeFiles/pancake.dir/src/Log.cpp.i
.PHONY : src/Log.cpp.i

src/Log.s: src/Log.cpp.s

.PHONY : src/Log.s

# target to generate assembly for a file
src/Log.cpp.s:
	$(MAKE) -f CMakeFiles/pancake.dir/build.make CMakeFiles/pancake.dir/src/Log.cpp.s
.PHONY : src/Log.cpp.s

src/Map.o: src/Map.cpp.o

.PHONY : src/Map.o

# target to build an object file
src/Map.cpp.o:
	$(MAKE) -f CMakeFiles/pancake.dir/build.make CMakeFiles/pancake.dir/src/Map.cpp.o
.PHONY : src/Map.cpp.o

src/Map.i: src/Map.cpp.i

.PHONY : src/Map.i

# target to preprocess a source file
src/Map.cpp.i:
	$(MAKE) -f CMakeFiles/pancake.dir/build.make CMakeFiles/pancake.dir/src/Map.cpp.i
.PHONY : src/Map.cpp.i

src/Map.s: src/Map.cpp.s

.PHONY : src/Map.s

# target to generate assembly for a file
src/Map.cpp.s:
	$(MAKE) -f CMakeFiles/pancake.dir/build.make CMakeFiles/pancake.dir/src/Map.cpp.s
.PHONY : src/Map.cpp.s

src/MapLoader.o: src/MapLoader.cpp.o

.PHONY : src/MapLoader.o

# target to build an object file
src/MapLoader.cpp.o:
	$(MAKE) -f CMakeFiles/pancake.dir/build.make CMakeFiles/pancake.dir/src/MapLoader.cpp.o
.PHONY : src/MapLoader.cpp.o

src/MapLoader.i: src/MapLoader.cpp.i

.PHONY : src/MapLoader.i

# target to preprocess a source file
src/MapLoader.cpp.i:
	$(MAKE) -f CMakeFiles/pancake.dir/build.make CMakeFiles/pancake.dir/src/MapLoader.cpp.i
.PHONY : src/MapLoader.cpp.i

src/MapLoader.s: src/MapLoader.cpp.s

.PHONY : src/MapLoader.s

# target to generate assembly for a file
src/MapLoader.cpp.s:
	$(MAKE) -f CMakeFiles/pancake.dir/build.make CMakeFiles/pancake.dir/src/MapLoader.cpp.s
.PHONY : src/MapLoader.cpp.s

src/MapRenderer.o: src/MapRenderer.cpp.o

.PHONY : src/MapRenderer.o

# target to build an object file
src/MapRenderer.cpp.o:
	$(MAKE) -f CMakeFiles/pancake.dir/build.make CMakeFiles/pancake.dir/src/MapRenderer.cpp.o
.PHONY : src/MapRenderer.cpp.o

src/MapRenderer.i: src/MapRenderer.cpp.i

.PHONY : src/MapRenderer.i

# target to preprocess a source file
src/MapRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/pancake.dir/build.make CMakeFiles/pancake.dir/src/MapRenderer.cpp.i
.PHONY : src/MapRenderer.cpp.i

src/MapRenderer.s: src/MapRenderer.cpp.s

.PHONY : src/MapRenderer.s

# target to generate assembly for a file
src/MapRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/pancake.dir/build.make CMakeFiles/pancake.dir/src/MapRenderer.cpp.s
.PHONY : src/MapRenderer.cpp.s

src/Pancake.o: src/Pancake.cpp.o

.PHONY : src/Pancake.o

# target to build an object file
src/Pancake.cpp.o:
	$(MAKE) -f CMakeFiles/pancake.dir/build.make CMakeFiles/pancake.dir/src/Pancake.cpp.o
.PHONY : src/Pancake.cpp.o

src/Pancake.i: src/Pancake.cpp.i

.PHONY : src/Pancake.i

# target to preprocess a source file
src/Pancake.cpp.i:
	$(MAKE) -f CMakeFiles/pancake.dir/build.make CMakeFiles/pancake.dir/src/Pancake.cpp.i
.PHONY : src/Pancake.cpp.i

src/Pancake.s: src/Pancake.cpp.s

.PHONY : src/Pancake.s

# target to generate assembly for a file
src/Pancake.cpp.s:
	$(MAKE) -f CMakeFiles/pancake.dir/build.make CMakeFiles/pancake.dir/src/Pancake.cpp.s
.PHONY : src/Pancake.cpp.s

src/StringHelper.o: src/StringHelper.cpp.o

.PHONY : src/StringHelper.o

# target to build an object file
src/StringHelper.cpp.o:
	$(MAKE) -f CMakeFiles/pancake.dir/build.make CMakeFiles/pancake.dir/src/StringHelper.cpp.o
.PHONY : src/StringHelper.cpp.o

src/StringHelper.i: src/StringHelper.cpp.i

.PHONY : src/StringHelper.i

# target to preprocess a source file
src/StringHelper.cpp.i:
	$(MAKE) -f CMakeFiles/pancake.dir/build.make CMakeFiles/pancake.dir/src/StringHelper.cpp.i
.PHONY : src/StringHelper.cpp.i

src/StringHelper.s: src/StringHelper.cpp.s

.PHONY : src/StringHelper.s

# target to generate assembly for a file
src/StringHelper.cpp.s:
	$(MAKE) -f CMakeFiles/pancake.dir/build.make CMakeFiles/pancake.dir/src/StringHelper.cpp.s
.PHONY : src/StringHelper.cpp.s

src/TextureAtlas.o: src/TextureAtlas.cpp.o

.PHONY : src/TextureAtlas.o

# target to build an object file
src/TextureAtlas.cpp.o:
	$(MAKE) -f CMakeFiles/pancake.dir/build.make CMakeFiles/pancake.dir/src/TextureAtlas.cpp.o
.PHONY : src/TextureAtlas.cpp.o

src/TextureAtlas.i: src/TextureAtlas.cpp.i

.PHONY : src/TextureAtlas.i

# target to preprocess a source file
src/TextureAtlas.cpp.i:
	$(MAKE) -f CMakeFiles/pancake.dir/build.make CMakeFiles/pancake.dir/src/TextureAtlas.cpp.i
.PHONY : src/TextureAtlas.cpp.i

src/TextureAtlas.s: src/TextureAtlas.cpp.s

.PHONY : src/TextureAtlas.s

# target to generate assembly for a file
src/TextureAtlas.cpp.s:
	$(MAKE) -f CMakeFiles/pancake.dir/build.make CMakeFiles/pancake.dir/src/TextureAtlas.cpp.s
.PHONY : src/TextureAtlas.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... pancake"
	@echo "... src/Log.o"
	@echo "... src/Log.i"
	@echo "... src/Log.s"
	@echo "... src/Map.o"
	@echo "... src/Map.i"
	@echo "... src/Map.s"
	@echo "... src/MapLoader.o"
	@echo "... src/MapLoader.i"
	@echo "... src/MapLoader.s"
	@echo "... src/MapRenderer.o"
	@echo "... src/MapRenderer.i"
	@echo "... src/MapRenderer.s"
	@echo "... src/Pancake.o"
	@echo "... src/Pancake.i"
	@echo "... src/Pancake.s"
	@echo "... src/StringHelper.o"
	@echo "... src/StringHelper.i"
	@echo "... src/StringHelper.s"
	@echo "... src/TextureAtlas.o"
	@echo "... src/TextureAtlas.i"
	@echo "... src/TextureAtlas.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

